#          __                 __ __   __
#   .---.-|  .---.-.----.----|__|  |_|  |_.--.--.
#   |  _  |  |  _  |  __|   _|  |   _|   _|  |  |
#   |___._|__|___._|____|__| |__|____|____|___  |
#                                         |_____|

[env]
TERM = "xterm"
#WINIT_X11_SCALE_FACTOR = "1.8"
#WINIT_X11_SCALE_FACTOR = "2"

[cursor.style]
shape = "Underline"
blinking = "On"

[cursor]
thickness = 0.25
unfocused_hollow = false

[cursor.vi_mode_style]
shape = "Underline"
blinking = "On"

[font]
# For internal display
size = 5.5

# For external display
#size = 11.5

[font.bold]
#family = "spleen"
family = "CozetteVectorBold"
#family = "creep"
style = "Bold"

[font.bold_italic]
#family = "spleen"
family = "CozetteVector"
#family= "creep"
style = "Bold Italic"

[font.glyph_offset]
#live_config_reload = true
x = 1
y = 1

[font.italic]
#family = "spleen"
family = "CozetteVector"
#family = "creep"
style = "Italic"

[font.normal]
#family = "hack"
family = "CozetteVector"
#family = "spleen"
#family = "creep"
style = "Regular"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
dynamic_padding = true
#multiplier = 3
opacity = 1.0

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 8
