#Config for 1080p display

[env]
TERM = "xterm"

[font]
# For internal display
size = 8.5 

[font.bold]
#family = "hack"
family = "CozetteVectorBold"
#family = "creep"
style = "Bold"

[font.bold_italic]
#family = "hack"
family = "CozetteVector"
#family= "creep"
style = "Bold Italic"

[font.glyph_offset]
#live_config_reload = true
x = 1
y = 1

[font.italic]
#family = "hack"
family = "CozetteVector"
#family = "creep"
style = "Italic"

[font.normal]
#family = "hack"
family = "CozetteVector"
#family = "creep"
style = "Regular"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
dynamic_padding = true
#multiplier = 3
opacity = 1.0

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 8
