general.import = ["~/dotfiles/alacritty/alacritty.toml"]

[env]
TERM = "xterm"
#WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 19.5 

[window]
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 30 
y = 12
