#!/run/current-system/sw/bin/bash

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly DOTFILES_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
readonly LOG_FILE="/tmp/nixsetup-$(date +%Y%m%d-%H%M%S).log"
readonly CURRENT_USER="$(whoami)"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

error() {
    log "ERROR: $*" >&2
    exit 1
}

bootstrap_git() {
    if ! command -v git >/dev/null 2>&1; then
        log "git not found — installing via nix-shell..."
        # Install git into the current profile for this session
        nix-env -iA nixpkgs.git 2>>"$LOG_FILE" || \
            error "Failed to install git. Try: nix-shell -p git --run 'bash $0'"
        log "git installed"
    fi
}

check_prerequisites() {
    log "Checking prerequisites..."

    bootstrap_git

    command -v nixos-rebuild >/dev/null || error "nixos-rebuild not found — are you on NixOS?"

    [[ -d "$DOTFILES_DIR" ]] || error "Dotfiles directory not found at $DOTFILES_DIR"
    [[ -f "$DOTFILES_DIR/flake.nix" ]] || error "flake.nix not found in $DOTFILES_DIR"
    [[ -f "$DOTFILES_DIR/scripts/bash/links.sh" ]] || error "links.sh not found"

    # Verify hardware config exists (generated by NixOS installer)
    if [[ ! -f /etc/nixos/hardware-configuration.nix ]]; then
        error "/etc/nixos/hardware-configuration.nix not found. Run nixos-generate-config first."
    fi

    log "Prerequisites satisfied"
}

replace_username() {
    if [[ "$CURRENT_USER" == "traum" ]]; then
        log "Username is already 'traum', skipping replacement"
        return 0
    fi

    log "Replacing 'traum' with '$CURRENT_USER' in dotfiles..."

    find "$DOTFILES_DIR" -type f \
        -not -path "*/.git/*" \
        -not -name "*.png" -not -name "*.jpg" -not -name "*.jpeg" \
        -not -name "*.gif" -not -name "*.ico" -not -name "*.svg" \
        -not -name "*.lock" \
        -exec grep -lI "traum" {} \; 2>/dev/null | while read -r file; do
        log "  Updating: $file"
        sed -i "s/traum/$CURRENT_USER/g" "$file"
    done

    log "Username replacement complete"
}

create_backup() {
    local backup_dir="$HOME/.config-backup-$(date +%Y%m%d-%H%M%S)"
    local has_existing=false

    local configs=(
        "$HOME/.config/i3"
        "$HOME/.config/alacritty"
        "$HOME/.config/polybar"
        "$HOME/.config/rofi"
        "$HOME/.xinitrc"
        "$HOME/.bashrc"
        "$HOME/.zshrc"
        "$HOME/.local/bin"
    )

    for config in "${configs[@]}"; do
        if [[ -e "$config" && ! -L "$config" ]]; then
            has_existing=true
            break
        fi
    done

    if ! $has_existing; then
        log "No existing configs to back up — fresh install detected"
        return 0
    fi

    log "Backing up existing configs to $backup_dir..."
    mkdir -p "$backup_dir"

    for config in "${configs[@]}"; do
        if [[ -e "$config" && ! -L "$config" ]]; then
            log "  Backing up: $config"
            cp -r "$config" "$backup_dir/" 2>/dev/null || true
        fi
    done

    log "Backup complete: $backup_dir"
}

setup_symlinks() {
    log "Creating symlinks..."
    chmod +x "$DOTFILES_DIR/scripts/bash/links.sh"
    "$DOTFILES_DIR/scripts/bash/links.sh" --backup || error "Symlink setup failed"
    log "Symlinks created"
}

build_system() {
    log "Building NixOS system (user: $CURRENT_USER)..."

    export USER="${USER:-$CURRENT_USER}"
    export SUDO_USER="${SUDO_USER:-$USER}"

    chmod +x "$DOTFILES_DIR/scripts/bash/nixbuild.sh"
    "$DOTFILES_DIR/scripts/bash/nixbuild.sh" || error "System build failed"

    log "System built successfully"
}

main() {
    log "========================================"
    log "  NixOS dotfiles setup"
    log "  Dotfiles: $DOTFILES_DIR"
    log "  User:     $CURRENT_USER"
    log "  Log:      $LOG_FILE"
    log "========================================"

    check_prerequisites
    replace_username
    create_backup
    setup_symlinks
    build_system

    log ""
    log "Setup complete!"
    log "  Run 'x' to start the X session (or reboot)"
    log "  Log saved to: $LOG_FILE"
}

trap 'error "Setup failed at line $LINENO — check $LOG_FILE"' ERR

main "$@"
