--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/traum/Wallpapers/NordWave.png"

-- Special
background="#101116"
foreground="#b7c6d7"
cursor="#b7c6d7"

-- Colors
color0="#101116"
color1="#637B92"
color2="#6E899E"
color3="#7694AC"
color4="#7E9FC1"
color5="#819EBC"
color6="#85A9BE"
color7="#b7c6d7"
color8="#808a96"
color9="#637B92"
color10="#6E899E"
color11="#7694AC"
color12="#7E9FC1"
color13="#819EBC"
color14="#85A9BE"
color15="#b7c6d7"
