--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/traum/Wallpapers/Shoreline.png"

-- Special
background="#0C0F14"
foreground="#e5e8ed"
cursor="#e5e8ed"

-- Colors
color0="#0C0F14"
color1="#929FB0"
color2="#9FADC0"
color3="#B0B9CA"
color4="#BBC3D3"
color5="#C6CDDB"
color6="#D2D8E6"
color7="#e5e8ed"
color8="#a0a2a5"
color9="#929FB0"
color10="#9FADC0"
color11="#B0B9CA"
color12="#BBC3D3"
color13="#C6CDDB"
color14="#D2D8E6"
color15="#e5e8ed"
