# Shell variables
# Generated by 'wal'
wallpaper='/home/traum/Wallpapers/Cyberpunk.png'

# Special
background='#01090C'
foreground='#cbf478'
cursor='#cbf478'

# Colors
color0='#01090C'
color1='#289805'
color2='#4EA70B'
color3='#62D107'
color4='#78FA01'
color5='#9FA109'
color6='#8CFE00'
color7='#cbf478'
color8='#8eaa54'
color9='#289805'
color10='#4EA70B'
color11='#62D107'
color12='#78FA01'
color13='#9FA109'
color14='#8CFE00'
color15='#cbf478'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
