# Shell variables
# Generated by 'wal'
wallpaper='/home/traum/Wallpapers/Queens1.jpg'

# Special
background='#040404'
foreground='#efe3e1'
cursor='#efe3e1'

# Colors
color0='#040404'
color1='#E62759'
color2='#E74E74'
color3='#7F827D'
color4='#EC6E8C'
color5='#EE9DAC'
color6='#CDB0B2'
color7='#efe3e1'
color8='#a79e9d'
color9='#E62759'
color10='#E74E74'
color11='#7F827D'
color12='#EC6E8C'
color13='#EE9DAC'
color14='#CDB0B2'
color15='#efe3e1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
