# Shell variables
# Generated by 'wal'
wallpaper='/home/traum/Wallpapers/Dunes.jpg'

# Special
background='#0d0d0d'
foreground='#d2d2d2'
cursor='#d2d2d2'

# Colors
color0='#0d0d0d'
color1='#585858'
color2='#676767'
color3='#787878'
color4='#878787'
color5='#989898'
color6='#A7A7A7'
color7='#d2d2d2'
color8='#939393'
color9='#585858'
color10='#676767'
color11='#787878'
color12='#878787'
color13='#989898'
color14='#A7A7A7'
color15='#d2d2d2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
