--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/traum/Wallpapers/Eva01_2.png"

-- Special
background="#100c12"
foreground="#d2cddd"
cursor="#d2cddd"

-- Colors
color0="#100c12"
color1="#6A4AA5"
color2="#8A7497"
color3="#8A5FE2"
color4="#8F63E7"
color5="#7897AE"
color6="#67CC82"
color7="#d2cddd"
color8="#938f9a"
color9="#6A4AA5"
color10="#8A7497"
color11="#8A5FE2"
color12="#8F63E7"
color13="#7897AE"
color14="#67CC82"
color15="#d2cddd"
